#ifndef _DEPTH_TYPE_HG_
#define _DEPTH_TYPE_HG_

enum GL_DEPTH_TYPE
{
	DEPTH_TYPE_LESS,
	DEPTH_TYPE_ALWAYS,
	DEPTH_TYPE_NEVER,	
	DEPTH_TYPE_EQUAL,
	DEPTH_TYPE_LEQUAL,
	DEPTH_TYPE_GREATER,
	DEPTH_TYPE_NOTEQUAL,
	DEPTH_TYPE_GEQUAL
};

#endif // !_DEPTH_TYPE_HG_
